co = 58

player_heart:
		.byte  0, 0,co,co, 0, 0, 0, 0, 0, 0, 0, 0,co,co, 0, 0
		.byte  0,co,co,co,co,co, 0, 0, 0, 0,co,co,co,co,co, 0
		.byte co,co,co,co,co,co,co, 0, 0,co,co,co,co,co,co,co
		.byte co,co,co,co,co,co,co, 0, 0,co,co,co,co,co,co,co
		.byte co,co,co,co,co,co,co,co,co,co,co,co,co,co,co,co
		.byte co,co,co,co,co,co,co,co,co,co,co,co,co,co,co,co
		.byte co,co,co,co,co,co,co,co,co,co,co,co,co,co,co,co
		.byte co,co,co,co,co,co,co,co,co,co,co,co,co,co,co,co
		.byte co,co,co,co,co,co,co,co,co,co,co,co,co,co,co,co
		.byte co,co,co,co,co,co,co,co,co,co,co,co,co,co,co,co
		.byte  0, 0,co,co,co,co,co,co,co,co,co,co,co,co, 0, 0
		.byte  0, 0,co,co,co,co,co,co,co,co,co,co,co,co, 0, 0
		.byte  0, 0, 0, 0,co,co,co,co,co,co,co,co, 0, 0, 0, 0
		.byte  0, 0, 0, 0,co,co,co,co,co,co,co,co, 0, 0, 0, 0
		.byte  0, 0, 0, 0, 0, 0,co,co,co,co, 0, 0, 0, 0, 0, 0
		.byte  0, 0, 0, 0, 0, 0,co,co,co,co, 0, 0, 0, 0, 0, 0